version: "3.9"

services:

  ytc-web-prod:
    container_name: ytc-frontend-prod-web
    image: cashmyers/ytc-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
