version: "3.9"

services:

  nginx:
    container_name: ytc-nginx
    image: cashmyers/ytc-nginx
    ports:
      - 80:80
    depends_on:
      - ytc-web-fs

  ytc-web-fs:
    container_name: ytc-frontend-fs
    image: cashmyers/ytc-frontend-prod
    ports:
      - 3000:80