version: '3.9'

services:

  ytc-web-dev:
    container_name: ytc-frontend-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '/app/node_modules'
      - '.:/app'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  # ytc-test-dev:
  #   container_name: ytc-frontend-test-dev
  #   image: ytc-fullstack_ytc-frontend-web
  #   volumes:
  #     - '/app/node_modules'
  #     - '.:/app'
  #   command: [ "npm", "run", "test" ]
